FROM jenkins/jenkins:2.303.2-lts-jdk11
LABEL maintainer=ILKILABS
USER root
RUN apt update && apt install -yqq wget tar
RUN wget https://download.docker.com/linux/static/stable/x86_64/docker-20.10.9.tgz
RUN tar -xvf docker-20.10.9.tgz
RUN mv /docker/docker /bin/docker
RUN chmod +x /bin/docker
RUN rm -rf /docker
